// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "ai.plugin/scheduler/pkg/client/clientset/versioned/typed/resource/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeResourceV1alpha1 struct {
	*testing.Fake
}

func (c *FakeResourceV1alpha1) MachineInfos(namespace string) v1alpha1.MachineInfoInterface {
	return &FakeMachineInfos{c, namespace}
}

func (c *FakeResourceV1alpha1) MachineInfoLists(namespace string) v1alpha1.MachineInfoListInterface {
	return &FakeMachineInfoLists{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeResourceV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
