// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "ai.plugin/scheduler/apis/resource/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineInfos implements MachineInfoInterface
type FakeMachineInfos struct {
	Fake *FakeResourceV1alpha1
	ns   string
}

var machineinfosResource = schema.GroupVersionResource{Group: "resource.node.io", Version: "v1alpha1", Resource: "machineinfos"}

var machineinfosKind = schema.GroupVersionKind{Group: "resource.node.io", Version: "v1alpha1", Kind: "MachineInfo"}

// Get takes name of the machineInfo, and returns the corresponding machineInfo object, and an error if there is any.
func (c *FakeMachineInfos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MachineInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machineinfosResource, c.ns, name), &v1alpha1.MachineInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfo), err
}

// List takes label and field selectors, and returns the list of MachineInfos that match those selectors.
func (c *FakeMachineInfos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MachineInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machineinfosResource, machineinfosKind, c.ns, opts), &v1alpha1.MachineInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MachineInfoList{ListMeta: obj.(*v1alpha1.MachineInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.MachineInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineInfos.
func (c *FakeMachineInfos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machineinfosResource, c.ns, opts))

}

// Create takes the representation of a machineInfo and creates it.  Returns the server's representation of the machineInfo, and an error, if there is any.
func (c *FakeMachineInfos) Create(ctx context.Context, machineInfo *v1alpha1.MachineInfo, opts v1.CreateOptions) (result *v1alpha1.MachineInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machineinfosResource, c.ns, machineInfo), &v1alpha1.MachineInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfo), err
}

// Update takes the representation of a machineInfo and updates it. Returns the server's representation of the machineInfo, and an error, if there is any.
func (c *FakeMachineInfos) Update(ctx context.Context, machineInfo *v1alpha1.MachineInfo, opts v1.UpdateOptions) (result *v1alpha1.MachineInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machineinfosResource, c.ns, machineInfo), &v1alpha1.MachineInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfo), err
}

// Delete takes name of the machineInfo and deletes it. Returns an error if one occurs.
func (c *FakeMachineInfos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machineinfosResource, c.ns, name), &v1alpha1.MachineInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineInfos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machineinfosResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MachineInfoList{})
	return err
}

// Patch applies the patch and returns the patched machineInfo.
func (c *FakeMachineInfos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machineinfosResource, c.ns, name, pt, data, subresources...), &v1alpha1.MachineInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfo), err
}
