// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "ai.plugin/scheduler/apis/resource/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineInfoLists implements MachineInfoListInterface
type FakeMachineInfoLists struct {
	Fake *FakeResourceV1alpha1
	ns   string
}

var machineinfolistsResource = schema.GroupVersionResource{Group: "resource.node.io", Version: "v1alpha1", Resource: "machineinfolists"}

var machineinfolistsKind = schema.GroupVersionKind{Group: "resource.node.io", Version: "v1alpha1", Kind: "MachineInfoList"}

// Get takes name of the machineInfoList, and returns the corresponding machineInfoList object, and an error if there is any.
func (c *FakeMachineInfoLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MachineInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machineinfolistsResource, c.ns, name), &v1alpha1.MachineInfoList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfoList), err
}

// List takes label and field selectors, and returns the list of MachineInfoLists that match those selectors.
func (c *FakeMachineInfoLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MachineInfoListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machineinfolistsResource, machineinfolistsKind, c.ns, opts), &v1alpha1.MachineInfoListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfoListList), err
}

// Watch returns a watch.Interface that watches the requested machineInfoLists.
func (c *FakeMachineInfoLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machineinfolistsResource, c.ns, opts))

}

// Create takes the representation of a machineInfoList and creates it.  Returns the server's representation of the machineInfoList, and an error, if there is any.
func (c *FakeMachineInfoLists) Create(ctx context.Context, machineInfoList *v1alpha1.MachineInfoList, opts v1.CreateOptions) (result *v1alpha1.MachineInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machineinfolistsResource, c.ns, machineInfoList), &v1alpha1.MachineInfoList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfoList), err
}

// Update takes the representation of a machineInfoList and updates it. Returns the server's representation of the machineInfoList, and an error, if there is any.
func (c *FakeMachineInfoLists) Update(ctx context.Context, machineInfoList *v1alpha1.MachineInfoList, opts v1.UpdateOptions) (result *v1alpha1.MachineInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machineinfolistsResource, c.ns, machineInfoList), &v1alpha1.MachineInfoList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfoList), err
}

// Delete takes name of the machineInfoList and deletes it. Returns an error if one occurs.
func (c *FakeMachineInfoLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machineinfolistsResource, c.ns, name), &v1alpha1.MachineInfoList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineInfoLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machineinfolistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MachineInfoListList{})
	return err
}

// Patch applies the patch and returns the patched machineInfoList.
func (c *FakeMachineInfoLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machineinfolistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MachineInfoList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineInfoList), err
}
