// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "ai.plugin/scheduler/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MachineInfos returns a MachineInfoInformer.
	MachineInfos() MachineInfoInformer
	// MachineInfoLists returns a MachineInfoListInformer.
	MachineInfoLists() MachineInfoListInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// MachineInfos returns a MachineInfoInformer.
func (v *version) MachineInfos() MachineInfoInformer {
	return &machineInfoInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MachineInfoLists returns a MachineInfoListInformer.
func (v *version) MachineInfoLists() MachineInfoListInformer {
	return &machineInfoListInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
