//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	net "net"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CPUDetails) DeepCopyInto(out *CPUDetails) {
	{
		in := &in
		*out = make(CPUDetails, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUDetails.
func (in CPUDetails) DeepCopy() CPUDetails {
	if in == nil {
		return nil
	}
	out := new(CPUDetails)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUInfo) DeepCopyInto(out *CPUInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUInfo.
func (in *CPUInfo) DeepCopy() *CPUInfo {
	if in == nil {
		return nil
	}
	out := new(CPUInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUTopology) DeepCopyInto(out *CPUTopology) {
	*out = *in
	if in.NUMANodeIDToSocketID != nil {
		in, out := &in.NUMANodeIDToSocketID, &out.NUMANodeIDToSocketID
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CPUDetails != nil {
		in, out := &in.CPUDetails, &out.CPUDetails
		*out = make(CPUDetails, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUTopology.
func (in *CPUTopology) DeepCopy() *CPUTopology {
	if in == nil {
		return nil
	}
	out := new(CPUTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cache) DeepCopyInto(out *Cache) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cache.
func (in *Cache) DeepCopy() *Cache {
	if in == nil {
		return nil
	}
	out := new(Cache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CadvisorMachineInfo) DeepCopyInto(out *CadvisorMachineInfo) {
	*out = *in
	if in.MemoryByType != nil {
		in, out := &in.MemoryByType, &out.MemoryByType
		*out = make(map[string]*MemoryInfo, len(*in))
		for key, val := range *in {
			var outVal *MemoryInfo
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(MemoryInfo)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	out.NVMInfo = in.NVMInfo
	if in.HugePages != nil {
		in, out := &in.HugePages, &out.HugePages
		*out = make([]HugePagesInfo, len(*in))
		copy(*out, *in)
	}
	if in.Filesystems != nil {
		in, out := &in.Filesystems, &out.Filesystems
		*out = make([]FsInfo, len(*in))
		copy(*out, *in)
	}
	if in.DiskMap != nil {
		in, out := &in.DiskMap, &out.DiskMap
		*out = make(map[string]DiskInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NetworkDevices != nil {
		in, out := &in.NetworkDevices, &out.NetworkDevices
		*out = make([]NetInfo, len(*in))
		copy(*out, *in)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make([]Node, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CadvisorMachineInfo.
func (in *CadvisorMachineInfo) DeepCopy() *CadvisorMachineInfo {
	if in == nil {
		return nil
	}
	out := new(CadvisorMachineInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Core) DeepCopyInto(out *Core) {
	*out = *in
	if in.Threads != nil {
		in, out := &in.Threads, &out.Threads
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Caches != nil {
		in, out := &in.Caches, &out.Caches
		*out = make([]Cache, len(*in))
		copy(*out, *in)
	}
	if in.UncoreCaches != nil {
		in, out := &in.UncoreCaches, &out.UncoreCaches
		*out = make([]Cache, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Core.
func (in *Core) DeepCopy() *Core {
	if in == nil {
		return nil
	}
	out := new(Core)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskInfo) DeepCopyInto(out *DiskInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskInfo.
func (in *DiskInfo) DeepCopy() *DiskInfo {
	if in == nil {
		return nil
	}
	out := new(DiskInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Empty) DeepCopyInto(out *Empty) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Empty.
func (in *Empty) DeepCopy() *Empty {
	if in == nil {
		return nil
	}
	out := new(Empty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraCPUInfo) DeepCopyInto(out *ExtraCPUInfo) {
	*out = *in
	if in.SupportInstructionSet != nil {
		in, out := &in.SupportInstructionSet, &out.SupportInstructionSet
		*out = make(String, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraCPUInfo.
func (in *ExtraCPUInfo) DeepCopy() *ExtraCPUInfo {
	if in == nil {
		return nil
	}
	out := new(ExtraCPUInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraNetworkInfo) DeepCopyInto(out *ExtraNetworkInfo) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = make([]InterfaceInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraNetworkInfo.
func (in *ExtraNetworkInfo) DeepCopy() *ExtraNetworkInfo {
	if in == nil {
		return nil
	}
	out := new(ExtraNetworkInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraTopologyInfo) DeepCopyInto(out *ExtraTopologyInfo) {
	*out = *in
	if in.NumaDistanceMap != nil {
		in, out := &in.NumaDistanceMap, &out.NumaDistanceMap
		*out = make(map[string][]NumaDistanceInfo, len(*in))
		for key, val := range *in {
			var outVal []NumaDistanceInfo
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]NumaDistanceInfo, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.SiblingNumaInfo != nil {
		in, out := &in.SiblingNumaInfo, &out.SiblingNumaInfo
		*out = new(SiblingNumaInfo)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraTopologyInfo.
func (in *ExtraTopologyInfo) DeepCopy() *ExtraTopologyInfo {
	if in == nil {
		return nil
	}
	out := new(ExtraTopologyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FsInfo) DeepCopyInto(out *FsInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FsInfo.
func (in *FsInfo) DeepCopy() *FsInfo {
	if in == nil {
		return nil
	}
	out := new(FsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugePagesInfo) DeepCopyInto(out *HugePagesInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugePagesInfo.
func (in *HugePagesInfo) DeepCopy() *HugePagesInfo {
	if in == nil {
		return nil
	}
	out := new(HugePagesInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IfaceAddr) DeepCopyInto(out *IfaceAddr) {
	*out = *in
	if in.IPV4 != nil {
		in, out := &in.IPV4, &out.IPV4
		*out = make([]*net.IP, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(net.IP)
				if **in != nil {
					in, out := *in, *out
					*out = make([]byte, len(*in))
					copy(*out, *in)
				}
			}
		}
	}
	if in.IPV6 != nil {
		in, out := &in.IPV6, &out.IPV6
		*out = make([]*net.IP, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(net.IP)
				if **in != nil {
					in, out := *in, *out
					*out = make([]byte, len(*in))
					copy(*out, *in)
				}
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IfaceAddr.
func (in *IfaceAddr) DeepCopy() *IfaceAddr {
	if in == nil {
		return nil
	}
	out := new(IfaceAddr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Int) DeepCopyInto(out *Int) {
	{
		in := &in
		*out = make(Int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Int.
func (in Int) DeepCopy() Int {
	if in == nil {
		return nil
	}
	out := new(Int)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceInfo) DeepCopyInto(out *InterfaceInfo) {
	*out = *in
	if in.Addr != nil {
		in, out := &in.Addr, &out.Addr
		*out = new(IfaceAddr)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceInfo.
func (in *InterfaceInfo) DeepCopy() *InterfaceInfo {
	if in == nil {
		return nil
	}
	out := new(InterfaceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineInfo) DeepCopyInto(out *MachineInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineInfo.
func (in *MachineInfo) DeepCopy() *MachineInfo {
	if in == nil {
		return nil
	}
	out := new(MachineInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineInfoList) DeepCopyInto(out *MachineInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineInfoList.
func (in *MachineInfoList) DeepCopy() *MachineInfoList {
	if in == nil {
		return nil
	}
	out := new(MachineInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineInfoSpec) DeepCopyInto(out *MachineInfoSpec) {
	*out = *in
	if in.MachineInfo != nil {
		in, out := &in.MachineInfo, &out.MachineInfo
		*out = new(CadvisorMachineInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUTopology != nil {
		in, out := &in.CPUTopology, &out.CPUTopology
		*out = new(CPUTopology)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryTopology != nil {
		in, out := &in.MemoryTopology, &out.MemoryTopology
		*out = new(MemoryTopology)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraCPUInfo != nil {
		in, out := &in.ExtraCPUInfo, &out.ExtraCPUInfo
		*out = new(ExtraCPUInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraNetworkInfo != nil {
		in, out := &in.ExtraNetworkInfo, &out.ExtraNetworkInfo
		*out = new(ExtraNetworkInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraTopologyInfo != nil {
		in, out := &in.ExtraTopologyInfo, &out.ExtraTopologyInfo
		*out = new(ExtraTopologyInfo)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineInfoSpec.
func (in *MachineInfoSpec) DeepCopy() *MachineInfoSpec {
	if in == nil {
		return nil
	}
	out := new(MachineInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MemoryDetails) DeepCopyInto(out *MemoryDetails) {
	{
		in := &in
		*out = make(MemoryDetails, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryDetails.
func (in MemoryDetails) DeepCopy() MemoryDetails {
	if in == nil {
		return nil
	}
	out := new(MemoryDetails)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryInfo) DeepCopyInto(out *MemoryInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryInfo.
func (in *MemoryInfo) DeepCopy() *MemoryInfo {
	if in == nil {
		return nil
	}
	out := new(MemoryInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryTopology) DeepCopyInto(out *MemoryTopology) {
	*out = *in
	if in.MemoryDetails != nil {
		in, out := &in.MemoryDetails, &out.MemoryDetails
		*out = make(MemoryDetails, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryTopology.
func (in *MemoryTopology) DeepCopy() *MemoryTopology {
	if in == nil {
		return nil
	}
	out := new(MemoryTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVMInfo) DeepCopyInto(out *NVMInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVMInfo.
func (in *NVMInfo) DeepCopy() *NVMInfo {
	if in == nil {
		return nil
	}
	out := new(NVMInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetInfo) DeepCopyInto(out *NetInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetInfo.
func (in *NetInfo) DeepCopy() *NetInfo {
	if in == nil {
		return nil
	}
	out := new(NetInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Node) DeepCopyInto(out *Node) {
	*out = *in
	if in.HugePages != nil {
		in, out := &in.HugePages, &out.HugePages
		*out = make([]HugePagesInfo, len(*in))
		copy(*out, *in)
	}
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		*out = make([]Core, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Caches != nil {
		in, out := &in.Caches, &out.Caches
		*out = make([]Cache, len(*in))
		copy(*out, *in)
	}
	if in.Distances != nil {
		in, out := &in.Distances, &out.Distances
		*out = make([]uint64, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Node.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	out := new(Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NumaDistanceInfo) DeepCopyInto(out *NumaDistanceInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NumaDistanceInfo.
func (in *NumaDistanceInfo) DeepCopy() *NumaDistanceInfo {
	if in == nil {
		return nil
	}
	out := new(NumaDistanceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiblingNumaInfo) DeepCopyInto(out *SiblingNumaInfo) {
	*out = *in
	if in.SiblingNumaMap != nil {
		in, out := &in.SiblingNumaMap, &out.SiblingNumaMap
		*out = make(map[string]Int, len(*in))
		for key, val := range *in {
			var outVal map[string]Empty
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(Int, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SiblingNumaAvgMBWAllocatableMap != nil {
		in, out := &in.SiblingNumaAvgMBWAllocatableMap, &out.SiblingNumaAvgMBWAllocatableMap
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SiblingNumaAvgMBWCapacityMap != nil {
		in, out := &in.SiblingNumaAvgMBWCapacityMap, &out.SiblingNumaAvgMBWCapacityMap
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiblingNumaInfo.
func (in *SiblingNumaInfo) DeepCopy() *SiblingNumaInfo {
	if in == nil {
		return nil
	}
	out := new(SiblingNumaInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in String) DeepCopyInto(out *String) {
	{
		in := &in
		*out = make(String, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new String.
func (in String) DeepCopy() String {
	if in == nil {
		return nil
	}
	out := new(String)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInfo) DeepCopyInto(out *VersionInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInfo.
func (in *VersionInfo) DeepCopy() *VersionInfo {
	if in == nil {
		return nil
	}
	out := new(VersionInfo)
	in.DeepCopyInto(out)
	return out
}
