// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "ai.plugin/scheduler/apis/resource/v1alpha1"
	scheme "ai.plugin/scheduler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MachineInfoListsGetter has a method to return a MachineInfoListInterface.
// A group's client should implement this interface.
type MachineInfoListsGetter interface {
	MachineInfoLists(namespace string) MachineInfoListInterface
}

// MachineInfoListInterface has methods to work with MachineInfoList resources.
type MachineInfoListInterface interface {
	Create(ctx context.Context, machineInfoList *v1alpha1.MachineInfoList, opts v1.CreateOptions) (*v1alpha1.MachineInfoList, error)
	Update(ctx context.Context, machineInfoList *v1alpha1.MachineInfoList, opts v1.UpdateOptions) (*v1alpha1.MachineInfoList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MachineInfoList, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MachineInfoListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineInfoList, err error)
	MachineInfoListExpansion
}

// machineInfoLists implements MachineInfoListInterface
type machineInfoLists struct {
	client rest.Interface
	ns     string
}

// newMachineInfoLists returns a MachineInfoLists
func newMachineInfoLists(c *ResourceV1alpha1Client, namespace string) *machineInfoLists {
	return &machineInfoLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineInfoList, and returns the corresponding machineInfoList object, and an error if there is any.
func (c *machineInfoLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MachineInfoList, err error) {
	result = &v1alpha1.MachineInfoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machineinfolists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineInfoLists that match those selectors.
func (c *machineInfoLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MachineInfoListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MachineInfoListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machineinfolists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineInfoLists.
func (c *machineInfoLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machineinfolists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a machineInfoList and creates it.  Returns the server's representation of the machineInfoList, and an error, if there is any.
func (c *machineInfoLists) Create(ctx context.Context, machineInfoList *v1alpha1.MachineInfoList, opts v1.CreateOptions) (result *v1alpha1.MachineInfoList, err error) {
	result = &v1alpha1.MachineInfoList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machineinfolists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(machineInfoList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a machineInfoList and updates it. Returns the server's representation of the machineInfoList, and an error, if there is any.
func (c *machineInfoLists) Update(ctx context.Context, machineInfoList *v1alpha1.MachineInfoList, opts v1.UpdateOptions) (result *v1alpha1.MachineInfoList, err error) {
	result = &v1alpha1.MachineInfoList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machineinfolists").
		Name(machineInfoList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(machineInfoList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the machineInfoList and deletes it. Returns an error if one occurs.
func (c *machineInfoLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machineinfolists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineInfoLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machineinfolists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched machineInfoList.
func (c *machineInfoLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineInfoList, err error) {
	result = &v1alpha1.MachineInfoList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machineinfolists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
