// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// MachineInfoListerExpansion allows custom methods to be added to
// MachineInfoLister.
type MachineInfoListerExpansion interface{}

// MachineInfoNamespaceListerExpansion allows custom methods to be added to
// MachineInfoNamespaceLister.
type MachineInfoNamespaceListerExpansion interface{}
