// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "ai.plugin/scheduler/apis/resource/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MachineInfoListLister helps list MachineInfoLists.
// All objects returned here must be treated as read-only.
type MachineInfoListLister interface {
	// List lists all MachineInfoLists in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MachineInfoList, err error)
	// MachineInfoLists returns an object that can list and get MachineInfoLists.
	MachineInfoLists(namespace string) MachineInfoListNamespaceLister
	MachineInfoListListerExpansion
}

// machineInfoListLister implements the MachineInfoListLister interface.
type machineInfoListLister struct {
	indexer cache.Indexer
}

// NewMachineInfoListLister returns a new MachineInfoListLister.
func NewMachineInfoListLister(indexer cache.Indexer) MachineInfoListLister {
	return &machineInfoListLister{indexer: indexer}
}

// List lists all MachineInfoLists in the indexer.
func (s *machineInfoListLister) List(selector labels.Selector) (ret []*v1alpha1.MachineInfoList, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineInfoList))
	})
	return ret, err
}

// MachineInfoLists returns an object that can list and get MachineInfoLists.
func (s *machineInfoListLister) MachineInfoLists(namespace string) MachineInfoListNamespaceLister {
	return machineInfoListNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MachineInfoListNamespaceLister helps list and get MachineInfoLists.
// All objects returned here must be treated as read-only.
type MachineInfoListNamespaceLister interface {
	// List lists all MachineInfoLists in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MachineInfoList, err error)
	// Get retrieves the MachineInfoList from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.MachineInfoList, error)
	MachineInfoListNamespaceListerExpansion
}

// machineInfoListNamespaceLister implements the MachineInfoListNamespaceLister
// interface.
type machineInfoListNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MachineInfoLists in the indexer for a given namespace.
func (s machineInfoListNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MachineInfoList, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineInfoList))
	})
	return ret, err
}

// Get retrieves the MachineInfoList from the indexer for a given namespace and name.
func (s machineInfoListNamespaceLister) Get(name string) (*v1alpha1.MachineInfoList, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("machineinfolist"), name)
	}
	return obj.(*v1alpha1.MachineInfoList), nil
}
