// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "ai.plugin/scheduler/apis/resource/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MachineInfoLister helps list MachineInfos.
// All objects returned here must be treated as read-only.
type MachineInfoLister interface {
	// List lists all MachineInfos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error)
	// MachineInfos returns an object that can list and get MachineInfos.
	MachineInfos(namespace string) MachineInfoNamespaceLister
	MachineInfoListerExpansion
}

// machineInfoLister implements the MachineInfoLister interface.
type machineInfoLister struct {
	indexer cache.Indexer
}

// NewMachineInfoLister returns a new MachineInfoLister.
func NewMachineInfoLister(indexer cache.Indexer) MachineInfoLister {
	return &machineInfoLister{indexer: indexer}
}

// List lists all MachineInfos in the indexer.
func (s *machineInfoLister) List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineInfo))
	})
	return ret, err
}

// MachineInfos returns an object that can list and get MachineInfos.
func (s *machineInfoLister) MachineInfos(namespace string) MachineInfoNamespaceLister {
	return machineInfoNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MachineInfoNamespaceLister helps list and get MachineInfos.
// All objects returned here must be treated as read-only.
type MachineInfoNamespaceLister interface {
	// List lists all MachineInfos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error)
	// Get retrieves the MachineInfo from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.MachineInfo, error)
	MachineInfoNamespaceListerExpansion
}

// machineInfoNamespaceLister implements the MachineInfoNamespaceLister
// interface.
type machineInfoNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MachineInfos in the indexer for a given namespace.
func (s machineInfoNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineInfo))
	})
	return ret, err
}

// Get retrieves the MachineInfo from the indexer for a given namespace and name.
func (s machineInfoNamespaceLister) Get(name string) (*v1alpha1.MachineInfo, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("machineinfo"), name)
	}
	return obj.(*v1alpha1.MachineInfo), nil
}
